Explicitly set maxfee in CLN
btcpayserver/BTCPayServer.Lightning pull request #138
Opened 2023-09-06 00:35 UTC by kngako

From the CLN docs: 

> maxfee overrides both maxfeepercent and exemptfee defaults (and if you specify maxfee you cannot specify either of those), and creates an absolute limit on what fee we will pay. This allows you to implement your own heuristics rather than the primitive ones used here.

https://docs.corelightning.org/reference/lightning-pay

2023-09-06 10:33 UTC, dennisreimann requested changes
I think it needs to be rather like this, because if maxfee is set, feepercent shouldn't be set:

```csharp
var maxFeeFlat = payParams?.MaxFeeFlat;
var feePercent = maxFeeFlat is null ? payParams?.MaxFeePercent : null;
```

Also I think `maxFeeFlat` needs to be a millisat amount, so the conversion is not necessary. Haven't tested this yet.

2023-09-06 23:25 UTC, kngako commented
Great suggestion. I think the MaxFeeFlat is Satoshis becuase every other client specificies this value in sats. CLN is the only one that specifies it in millisats.

To not do the conversion here one could instantiate a LightMoney instance. But this seems  worse then just doing a conversion:

```
long? maxFeeFlat = payParams?.MaxFeeFlat is null ? null : new LightMoney(payParams?.MaxFeeFlat).MilliSatoshi;
```

2023-09-07 06:12 UTC, dennisreimann commented
I thought it'd be `LightMoney` already, but it's actually an instance of `Money`. So you're correct — go ahead and update the code so that we can see what the tests say :)

2023-09-07 20:25 UTC, kngako commented
Pushed

2023-09-08 07:44 UTC, dennisreimann approved these changes

2023-10-06 06:57 UTC, merged